/*
 * Copyright (C) 2015 
 * Patricia Lei Aglibot, Vincent Asotillo, Jermaine Geronimo, Bryan James Ilaga, Evander Louis Macandog, Nicole Mico
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package varietystore_managementsystem.UserInterface;

import java.awt.*;
import java.sql.*;
import static java.awt.GraphicsDevice.WindowTranslucency.*;

/**
 * <h1>LogIn Class</h1>
 * <p>This class/file is a part of Variety Store Management System</p>
 * <p>This class is the first frame to pop up upon user click.
 * This class contains user log in as well as the first connection
 * to the secure database.</p>
 * 
 * @author  Variety Store Management System Group
 * @version 1.0
 * @since   2015-03-15
 */
public class 
        LogIn extends javax.swing.JFrame 
{
    
    /*
     * Static Variables
     */
    protected Connection connection     =   null;
    private final String tableName      =   "user_tbl";
    private final String firstNameField =   "FirstName";
    private final String lastNameField  =   "LastName";
    private final String userIDField    =   "UserID";
    
    protected String firstName          =   "";
    protected String lastName           =   "";
    protected int UID                   =   0;
    
    private int pointX                  =   0;
    private int pointY                  =   0;
    
    /*
     * Creates new form UserInterface
     */
    public 
        LogIn() 
    {
        
        preInit();
        initComponents();
        userInit ();
        
    } // Constructor LogIn()
        
     /*
      * Encapsulators
      */
     private 
        String getTableName () 
     {
         return (tableName);
     }
     
     private 
        String getFirstNameColumn () {
         return (firstNameField);
     }
     
     private 
        String getLastNameColumn () 
     {
         return (lastNameField);
     }
     
     private 
        String getUserIDColumn () 
     {
         return (userIDField);
     }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCred = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        tfUsername = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        lblSampleUsername = new javax.swing.JLabel();
        pnlSampleUsername = new javax.swing.JPanel();
        lblSamplePassword = new javax.swing.JLabel();
        pnlSamplePassword = new javax.swing.JPanel();
        pnlButton = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Variety Store Management System");
        setPreferredSize(new java.awt.Dimension(479, 321));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlCred.setBackground(new java.awt.Color (0, 0, 0, 190));
        pnlCred.setOpaque(false);
        pnlCred.setPreferredSize(new java.awt.Dimension(337, 100));
        pnlCred.setLayout(null);

        lblUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblUsername.setText("Username: ");
        pnlCred.add(lblUsername);
        lblUsername.setBounds(20, 20, 64, 24);

        lblPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblPassword.setText("Password:");
        pnlCred.add(lblPassword);
        lblPassword.setBounds(20, 50, 64, 27);

        tfUsername.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        tfUsername.setToolTipText("Enter registered username");
        tfUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        tfUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfUsernameFocusLost(evt);
            }
        });
        pnlCred.add(tfUsername);
        tfUsername.setBounds(110, 20, 200, 22);

        pfPassword.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        pfPassword.setToolTipText("Enter password");
        pfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        pfPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfPasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfPasswordFocusLost(evt);
            }
        });
        pnlCred.add(pfPassword);
        pfPassword.setBounds(110, 50, 200, 20);

        lblSampleUsername.setForeground(new java.awt.Color(153, 153, 153));
        lblSampleUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSampleUsername.setText("Edward_Chrono");
        lblSampleUsername.setOpaque(true);
        pnlCred.add(lblSampleUsername);
        lblSampleUsername.setBounds(120, 20, 190, 20);

        javax.swing.GroupLayout pnlSampleUsernameLayout = new javax.swing.GroupLayout(pnlSampleUsername);
        pnlSampleUsername.setLayout(pnlSampleUsernameLayout);
        pnlSampleUsernameLayout.setHorizontalGroup(
            pnlSampleUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnlSampleUsernameLayout.setVerticalGroup(
            pnlSampleUsernameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pnlCred.add(pnlSampleUsername);
        pnlSampleUsername.setBounds(110, 20, 200, 20);

        lblSamplePassword.setForeground(new java.awt.Color(153, 153, 153));
        lblSamplePassword.setText("••••••••");
        lblSamplePassword.setOpaque(true);
        pnlCred.add(lblSamplePassword);
        lblSamplePassword.setBounds(120, 50, 60, 20);

        getContentPane().add(pnlCred);
        pnlCred.setBounds(70, 120, 337, 100);

        javax.swing.GroupLayout pnlSamplePasswordLayout = new javax.swing.GroupLayout(pnlSamplePassword);
        pnlSamplePassword.setLayout(pnlSamplePasswordLayout);
        pnlSamplePasswordLayout.setHorizontalGroup(
            pnlSamplePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        pnlSamplePasswordLayout.setVerticalGroup(
            pnlSamplePasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(pnlSamplePassword);
        pnlSamplePassword.setBounds(180, 170, 200, 20);

        pnlButton.setBackground(new java.awt.Color (0, 0, 0, 190));
        pnlButton.setFont(new java.awt.Font("Courier New", 0, 11)); // NOI18N
        pnlButton.setOpaque(false);

        btnLogin.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        btnLogin.setText("Log In");
        btnLogin.setToolTipText("Log In");
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setToolTipText("Clear all fields");
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClearMouseExited(evt);
            }
        });
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setToolTipText("Exit");
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlButton);
        pnlButton.setBounds(70, 250, 340, 50);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/CloseButton.png"))); // NOI18N
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(450, 10, 20, 20);

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/MinimizeButton.png"))); // NOI18N
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        getContentPane().add(btnMin);
        btnMin.setBounds(420, 10, 20, 20);

        lblBackground.setBackground(new java.awt.Color (0, 0, 0, 0));
        lblBackground.setForeground(new java.awt.Color (0, 0, 0, 0));
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/LogIn.png"))); // NOI18N
        lblBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseDragged(evt);
            }
        });
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackgroundMousePressed(evt);
            }
        });
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 480, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        setOpacity(1.0f);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        setOpacity(0.7f);
    }//GEN-LAST:event_formWindowLostFocus

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        dispose ();
        System.exit (0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfUsername.setText ("");
        pfPassword.setText ("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:

        String tempUsername;
        String tempPassword;

        tempUsername = tfUsername.getText();
        tempPassword = new String (pfPassword.getPassword());

        try {

            int entryCount = 0;

            JavaConnector.DBConnection dbconnect = new JavaConnector.DBConnection ();
            connection = dbconnect.getConnection ();
            Statement stmt = connection.createStatement();
            String sql = "Select " + getFirstNameColumn() + ", " + getLastNameColumn() + ", " + getUserIDColumn() + " from " + getTableName() + " where username = '" + tempUsername + "' and password = '" + tempPassword + "';";
            ResultSet rs = stmt.executeQuery (sql);

            while (rs.next()) {
                firstName = rs.getString (getFirstNameColumn());
                lastName = rs.getString (getLastNameColumn());
                UID = rs.getInt(getUserIDColumn());
                
                entryCount++;
            }

            if (entryCount != 0) {
                String message = "Access Granted!\n" +
                "Welcome " + firstName + " " + lastName;
                javax.swing.JOptionPane.showMessageDialog (null, message, "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                CashRegister cr = new CashRegister (connection, UID);
                dispose ();
                cr.launchFrame ();

            } else {
                javax.swing.JOptionPane.showMessageDialog (null, "Access Denied! Please enter valid credentials", "Failed", javax.swing.JOptionPane.WARNING_MESSAGE);
            }
        } catch (NullPointerException npe) {
            System.err.println ("Null Pointer Exception Caught: " + npe);
        } catch (SQLException sqle) {
            System.err.println ("SQL Exception Caught: " + sqle);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        // TODO add your handling code here:
        // btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/login.png")));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        // TODO add your handling code here:
        // btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/loginGlow.png")));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnClearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseExited
        // TODO add your handling code here:
        // btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/clear.png")));
    }//GEN-LAST:event_btnClearMouseExited

    private void btnClearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseEntered
        // TODO add your handling code here:
        // btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/clearGlow.png")));
    }//GEN-LAST:event_btnClearMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        // btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/exit.png")));
    }//GEN-LAST:event_btnExitMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        // btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/LOGIN/exitGlow.png")));
    }//GEN-LAST:event_btnExitMouseEntered

    private void lblBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMousePressed
        // TODO add your handling code here:
        pointX = evt.getX();
        pointY = evt.getY();
    }//GEN-LAST:event_lblBackgroundMousePressed

    private void lblBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseDragged
        // TODO add your handling code here:
        setLocation (getLocation().x + evt.getX() - pointX, getLocation().y + evt.getY() - pointY);
    }//GEN-LAST:event_lblBackgroundMouseDragged

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose ();
        System.exit (0);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void tfUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusGained
        // TODO add your handling code here:
        lblSampleUsername.setOpaque (false);
        pnlSampleUsername.setOpaque (false);
        tfUsername.setOpaque (true);
    }//GEN-LAST:event_tfUsernameFocusGained

    private void tfUsernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameFocusLost
        // TODO add your handling code here:
        try {
            if (tfUsername.getText().trim().equals("")) {
                lblSampleUsername.setOpaque (true);
                pnlSampleUsername.setOpaque (true);
                tfUsername.setOpaque (false);
            }
        } catch (NullPointerException npe) {
            System.err.println (npe);
        }
    }//GEN-LAST:event_tfUsernameFocusLost

    private void pfPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusGained
        // TODO add your handling code here:
        lblSamplePassword.setOpaque (false);
        pnlSamplePassword.setOpaque (false);
        pfPassword.setOpaque (true);
    }//GEN-LAST:event_pfPasswordFocusGained

    private void pfPasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfPasswordFocusLost
        // TODO add your handling code here:
        if (new String (pfPassword.getPassword()).equals("")) {
            lblSamplePassword.setOpaque (true);
            pnlSamplePassword.setOpaque (true);
            pfPassword.setOpaque (false);
        }
    }//GEN-LAST:event_pfPasswordFocusLost
    
    private void 
        userInit () 
    {
        
        setTitle ("5J Sari-Sari Store");
        setLocationRelativeTo (null);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        
        if (!gd.isWindowTranslucencySupported(TRANSLUCENT)) {
            System.err.println ("Translucensy not supported.");
        }
        
    } // userInit()
        
    private void
            preInit()
    {
        setUndecorated(true);
    } // preInit()
    
    public void 
        launchFrame () 
    {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            setOpacity (1.0f);
            new LogIn().setVisible (true);
        });
    } // launchFrame()

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMin;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSamplePassword;
    private javax.swing.JLabel lblSampleUsername;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlCred;
    private javax.swing.JPanel pnlSamplePassword;
    private javax.swing.JPanel pnlSampleUsername;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
} // Class LogIn
