/*
 * Copyright (C) 2016 Variety Store Management System Group
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package varietystore_managementsystem.UserInterface;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import static java.awt.GraphicsDevice.WindowTranslucency.*;

/**
 *
 * @author Ilaga_Family
 */
public final class RegisterNew extends javax.swing.JFrame {
    
    final private String tableName      =   "user_tbl";
    final private String firstNameField =   "FirstName";
    final private String lastNameField  =   "LastName";
    final private String usernameField  =   "username";
    final private String passwordField  =   "password";
    final private String ageField       =   "age";
    final private String birthdateField =   "birthDate";
    final private String addressField   =   "address";
    final private String contactNumberField  =   "contactNumber";
    final private String userTypeField  =   "user_type";
    
    private String regFirstname   =   null;
    private String regLastname    =   null;
    private String regUsername    =   null;
    private String regPassword    =   null;
    private String regType        =   null;
    private int regMonth          =   0;
    private int regDay            =   0;
    private int regYear           =   0;
    private int regAge            =   0;
    private String regAddress     =   null;
    private String regNumber      =   null;
    
    protected Connection connection =   null;
    protected int UID               =   0;
    
    private int pointX              =   0;
    private int pointY              =   0;
    
    /**
     * Creates new form RegisterNew
     * @param connection
     * @param UID
     */
    protected RegisterNew(Connection connection, int UID) {
        
        setUndecorated (true);
        
        initComponents();
        this.userInit();
        
        this.connection = connection;
        this.UID = UID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfo = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCont = new javax.swing.JLabel();
        tfFirstName = new javax.swing.JTextField();
        tfLastName = new javax.swing.JTextField();
        tfUsername = new javax.swing.JTextField();
        tfPassword = new javax.swing.JTextField();
        lblUserType = new javax.swing.JLabel();
        cboUserType = new javax.swing.JComboBox<>();
        cboMonth = new javax.swing.JComboBox();
        spinnerDay = new javax.swing.JSpinner();
        spinnerYear = new javax.swing.JSpinner();
        tfAge = new javax.swing.JTextField();
        tfAddress = new javax.swing.JTextField();
        tfCont = new javax.swing.JTextField();
        pnlButtons = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("5J Sari-sari Store - Register User");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(576, 471));
        setPreferredSize(new java.awt.Dimension(576, 471));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlInfo.setBackground(new java.awt.Color (0, 0, 0, 190));
        pnlInfo.setForeground(new java.awt.Color(255, 255, 255));
        pnlInfo.setOpaque(false);

        lblFirstName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblFirstName.setText("First Name: ");

        lblLastName.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblLastName.setText("Last Name: ");

        lblUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblUsername.setText("Preferred Username: ");

        lblPassword.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblPassword.setText("Preferred Password: ");

        lblBirthdate.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblBirthdate.setText("Birthdate: ");

        lblAge.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblAge.setText("Age: ");

        lblAddress.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblAddress.setText("Address: ");

        lblCont.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblCont.setText("Contact Number: ");

        tfFirstName.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfFirstName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        tfFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFirstNameActionPerformed(evt);
            }
        });

        tfLastName.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfLastName.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));

        tfUsername.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfUsername.setToolTipText("");
        tfUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        tfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameActionPerformed(evt);
            }
        });

        tfPassword.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfPassword.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        tfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswordActionPerformed(evt);
            }
        });

        lblUserType.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblUserType.setText("User Type:");

        cboUserType.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        cboUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal User", "Administrator" }));
        cboUserType.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        cboUserType.setOpaque(false);

        cboMonth.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        cboMonth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        cboMonth.setToolTipText("Month");
        cboMonth.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        cboMonth.setOpaque(false);
        cboMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMonthActionPerformed(evt);
            }
        });

        spinnerDay.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        spinnerDay.setModel(new javax.swing.SpinnerListModel(new String[] {"1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31"}));
        spinnerDay.setToolTipText("Day");
        spinnerDay.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));

        spinnerYear.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        spinnerYear.setModel(new javax.swing.SpinnerListModel(new String[] {"1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015"}));
        spinnerYear.setToolTipText("Year");
        spinnerYear.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));

        tfAge.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfAge.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));

        tfAddress.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfAddress.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));
        tfAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfAddressActionPerformed(evt);
            }
        });

        tfCont.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        tfCont.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 102), new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlInfoLayout = new javax.swing.GroupLayout(pnlInfo);
        pnlInfo.setLayout(pnlInfoLayout);
        pnlInfoLayout.setHorizontalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPassword)
                            .addComponent(lblBirthdate)
                            .addComponent(lblAddress)
                            .addComponent(lblCont)
                            .addComponent(lblUserType))
                        .addGap(25, 25, 25)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlInfoLayout.createSequentialGroup()
                                .addComponent(cboMonth, 0, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinnerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(lblAge)
                                .addGap(18, 18, 18)
                                .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlInfoLayout.createSequentialGroup()
                                .addComponent(cboUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tfPassword)
                            .addComponent(tfAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfCont)))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFirstName)
                            .addComponent(lblLastName))
                        .addGap(86, 86, 86)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfLastName)
                            .addComponent(tfFirstName)))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addGap(18, 18, 18)
                        .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        pnlInfoLayout.setVerticalGroup(
            pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(tfFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLastName)
                    .addComponent(tfLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(tfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(tfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserType)
                    .addComponent(cboUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(spinnerDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAge)
                            .addComponent(tfAge, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spinnerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBirthdate)))
                    .addGroup(pnlInfoLayout.createSequentialGroup()
                        .addComponent(cboMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addGap(7, 7, 7)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(tfAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCont)
                    .addComponent(tfCont, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pnlInfo);
        pnlInfo.setBounds(20, 130, 530, 270);

        pnlButtons.setBackground(new java.awt.Color (0, 0, 0, 190));
        pnlButtons.setOpaque(false);
        pnlButtons.setPreferredSize(new java.awt.Dimension(509, 50));

        btnSubmit.setBackground(new java.awt.Color (0, 0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.setBorderPainted(false);
        btnSubmit.setContentAreaFilled(false);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color (0, 0, 0, 0));
        btnClear.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnClear.setText("Clear");
        btnClear.setBorderPainted(false);
        btnClear.setContentAreaFilled(false);
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color (0, 0, 0, 0));
        btnBack.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonsLayout = new javax.swing.GroupLayout(pnlButtons);
        pnlButtons.setLayout(pnlButtonsLayout);
        pnlButtonsLayout.setHorizontalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonsLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        pnlButtonsLayout.setVerticalGroup(
            pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(pnlButtons);
        pnlButtons.setBounds(20, 410, 530, 40);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/CloseButton.png"))); // NOI18N
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(550, 10, 20, 20);

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/MinimizeButton.png"))); // NOI18N
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        getContentPane().add(btnMin);
        btnMin.setBounds(520, 10, 20, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/RegisterBG.png"))); // NOI18N
        lblBackground.setToolTipText("");
        lblBackground.setPreferredSize(new java.awt.Dimension(576, 415));
        lblBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseDragged(evt);
            }
        });
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackgroundMousePressed(evt);
            }
        });
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 580, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        setOpacity (1.0f);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        setOpacity (0.7f);
    }//GEN-LAST:event_formWindowLostFocus

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        try {
            
            regFirstname = tfFirstName.getText().trim();
            regLastname = tfLastName.getText().trim();
            regUsername = tfUsername.getText().trim();
            regPassword = tfPassword.getText().trim();
            regType = cboUserType.getSelectedItem().toString().equals("administrator") ? "admin" : "normal";
            regMonth = cboMonth.getSelectedIndex() + 1;
            regDay = Integer.parseInt (spinnerDay.getValue().toString());
            regYear = Integer.parseInt (spinnerYear.getValue().toString());
            regAge = Integer.parseInt(tfAge.getText().trim());
            regAddress = tfAddress.getText().trim();
            regNumber = tfCont.getText().trim();
            
            if (regFirstname.equals("") || regLastname.equals("") || regUsername.equals("") || regPassword.equals("") || (regAge < 8 || regAge > 100) || regAddress.equals("") || regNumber.equals("")) {
                JOptionPane.showMessageDialog (null, "Please Enter valid credentials!", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                String sql = "INSERT INTO " + tableName + " (" + firstNameField + ", " + lastNameField + ", " + usernameField + ", " + passwordField + ", " + birthdateField + ", " + ageField + ", " + addressField + ", " + contactNumberField + ", " + userTypeField + ")\n"
                        + "values ('" + regFirstname + "', '" + regLastname + "', '" + regUsername + "', '" + regPassword + "', STR_TO_DATE(' " + regMonth + " / " + regDay + " / " + regYear + "', '%m / %d / %Y'), " + regAge + ", '" + regAddress + "', '" + regNumber + "', '" + regType + "');";
                Statement stmt = connection.createStatement();
                boolean isSent = stmt.execute(sql);
                
                if (!isSent) {
                    JOptionPane.showMessageDialog (null, "Registration Success!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                    CashRegister cr = new CashRegister (connection, UID);
                    cr.launchFrame();
                }
            }
        } catch (NullPointerException npe) {
            System.err.println ("Null Pointer: " + npe);
            JOptionPane.showMessageDialog (null, "Please Enter valid credentials!", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException sqle) {
            String report = "Database Error!\n" + sqle;
            System.err.println ("Problem with database: " + sqle);
            JOptionPane.showMessageDialog (null, report, "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException nfe) {
            System.err.println ("Parsing error: " + nfe);
            JOptionPane.showMessageDialog (null, "Please Enter valid credentials!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void tfFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFirstNameActionPerformed

    private void tfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswordActionPerformed

    private void cboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMonthActionPerformed

    private void tfAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfAddressActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        CashRegister cr = new CashRegister (connection, UID);
        cr.launchFrame ();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        tfFirstName.setText ("");
        tfLastName.setText ("");
        tfUsername.setText ("");
        tfPassword.setText ("");
        cboMonth.setSelectedIndex (0);
        spinnerDay.setValue(1920);
        spinnerYear.setValue (1920);
        tfAge.setText ("");
        tfAddress.setText ("");
        tfCont.setText ("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void tfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsernameActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int choose = JOptionPane.showConfirmDialog (null, "Do You really want to exit?", "Confirm", JOptionPane.INFORMATION_MESSAGE);
        if (choose == JOptionPane.YES_OPTION) {
            dispose ();
            CashRegister cr = new CashRegister (connection, UID);
            cr.launchFrame ();
        }
    }//GEN-LAST:event_formWindowClosing

    private void lblBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMousePressed
        // TODO add your handling code here:
        pointX = evt.getX();
        pointY = evt.getY();
    }//GEN-LAST:event_lblBackgroundMousePressed

    private void lblBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseDragged
        // TODO add your handling code here:
        setLocation (getLocation().x + evt.getX() - pointX, getLocation().y + evt.getY() - pointY);
    }//GEN-LAST:event_lblBackgroundMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
        CashRegister cr = new CashRegister(connection, UID);
        cr.launchFrame();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinActionPerformed

    private void userInit() {
        setLocationRelativeTo (null);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        
        if (!gd.isWindowTranslucencySupported(TRANSLUCENT)) {
            System.err.println ("Translucensy not supported.");
        }
    } // userInit()
    
    public void launchFrame () {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            setOpacity (1.0f);
            new RegisterNew(connection, UID).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMin;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox cboMonth;
    private javax.swing.JComboBox<String> cboUserType;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblCont;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserType;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlInfo;
    private javax.swing.JSpinner spinnerDay;
    private javax.swing.JSpinner spinnerYear;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfAge;
    private javax.swing.JTextField tfCont;
    private javax.swing.JTextField tfFirstName;
    private javax.swing.JTextField tfLastName;
    private javax.swing.JTextField tfPassword;
    private javax.swing.JTextField tfUsername;
    // End of variables declaration//GEN-END:variables
}
