/*
 * Copyright (C) 2016 Ilaga_Family
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package varietystore_managementsystem.UserInterface;

import java.awt.*;
import javax.swing.*;
import java.sql.*;
import static java.awt.GraphicsDevice.WindowTranslucency.*;
import static varietystore_managementsystem.UserInterface.EditUser.connection;

/**
 *
 * @author Ilaga_Family
 */
public class ViewUser extends javax.swing.JFrame {
    
    final private String tableName      =   "user_tbl";
    
    Connection connection = null;
    int UID = 0;
    
    private int pointX                  =   0;
    private int pointY                  =   0;
    
    /**
     * Creates new form ViewUser
     * @param connection
     * @param UID
     */
    protected ViewUser(Connection connection, int UID) {
        setUndecorated (true);
        initComponents();
        this.userInit();
        
        this.connection = connection;
        this.UID = UID;
        this.fixComponent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCenter = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblBirthdate = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblCont = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        pnlPic = new javax.swing.JPanel();
        lblPic = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnMin = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("5J Sari-Sari Store - User Profile");
        setMinimumSize(new java.awt.Dimension(590, 411));
        setPreferredSize(new java.awt.Dimension(590, 411));
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        pnlCenter.setBackground(new java.awt.Color (0, 0, 0, 190));
        pnlCenter.setOpaque(false);

        lblName.setFont(new java.awt.Font("Bell MT", 1, 30)); // NOI18N
        lblName.setForeground(new java.awt.Color(204, 0, 0));
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblName.setText("NAME");
        lblName.setToolTipText("Employee Name");
        lblName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblUsername.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(51, 51, 51));
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblUsername.setText("USERNAME");
        lblUsername.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        lblBirthdate.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblBirthdate.setText("Birthdate: 01 / 01 / 1920");

        lblAge.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblAge.setText("Age: 00");

        lblAddress.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblAddress.setText("Address: #00");

        lblCont.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        lblCont.setText("Contact Number: 00000");

        btnBack.setFont(new java.awt.Font("Berlin Sans FB", 0, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.setBorderPainted(false);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        pnlPic.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(153, 153, 153)));

        lblPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/DefaultPic.jpg"))); // NOI18N

        javax.swing.GroupLayout pnlPicLayout = new javax.swing.GroupLayout(pnlPic);
        pnlPic.setLayout(pnlPicLayout);
        pnlPicLayout.setHorizontalGroup(
            pnlPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlPicLayout.setVerticalGroup(
            pnlPicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBirthdate)
                            .addComponent(lblAge)
                            .addComponent(lblAddress)
                            .addComponent(lblCont)))
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCenterLayout.createSequentialGroup()
                        .addComponent(pnlPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addContainerGap())
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(lblBirthdate)
                        .addGap(18, 18, 18)
                        .addComponent(lblAge)
                        .addGap(18, 18, 18)
                        .addComponent(lblAddress)))
                .addGap(20, 20, 20)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCont)
                    .addComponent(btnBack))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlCenter);
        pnlCenter.setBounds(30, 110, 530, 260);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/CloseButton.png"))); // NOI18N
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(560, 10, 20, 20);

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/MinimizeButton.png"))); // NOI18N
        btnMin.setBorderPainted(false);
        btnMin.setContentAreaFilled(false);
        btnMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinActionPerformed(evt);
            }
        });
        getContentPane().add(btnMin);
        btnMin.setBounds(530, 10, 20, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/varietystore_managementsystem/ELEMENTS/Register/ViewUserBG.png"))); // NOI18N
        lblBackground.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lblBackgroundMouseDragged(evt);
            }
        });
        lblBackground.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackgroundMousePressed(evt);
            }
        });
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 590, 411);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        setOpacity (1.0f);
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
        setOpacity (0.7f);
    }//GEN-LAST:event_formWindowLostFocus

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        dispose();
        CashRegister cr = new CashRegister (connection, UID);
        cr.launchFrame();
    }//GEN-LAST:event_formWindowClosing

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        dispose();
        CashRegister cr = new CashRegister (connection, UID);
        cr.launchFrame();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblBackgroundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMousePressed
        // TODO add your handling code here:
        pointX = evt.getX();
        pointY = evt.getY();
    }//GEN-LAST:event_lblBackgroundMousePressed

    private void lblBackgroundMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackgroundMouseDragged
        // TODO add your handling code here:
        setLocation (getLocation().x + evt.getX() - pointX, getLocation().y + evt.getY() - pointY);
    }//GEN-LAST:event_lblBackgroundMouseDragged

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
        CashRegister cr = new CashRegister(connection, UID);
        cr.launchFrame();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinActionPerformed
        // TODO add your handling code here:
        setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnMinActionPerformed
    
    public void userInit() {
        setLocationRelativeTo (null);
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice gd = ge.getDefaultScreenDevice();
        
        if (!gd.isWindowTranslucencySupported(TRANSLUCENT)) {
            System.err.println ("Translucensy not supported.");
        }
    }
    
    public void fixComponent() {
        
        try {
            Statement stmt = connection.createStatement();
            String sql = "Select * from " + tableName + " where userID = " + UID + ";";
            ResultSet rs = stmt.executeQuery (sql);
            
            while (rs.next()) {
                String name = rs.getString ("firstName") + " " + rs.getString ("lastName");
                String username = rs.getString ("username");
                java.util.Date bdate = rs.getDate ("birthDate");
                java.text.SimpleDateFormat sdt = new java.text.SimpleDateFormat ("MM / dd / yyyy");
                String birthdate = "Birthdate: " + sdt.format(bdate);
                int age = rs.getInt ("age");
                String address = rs.getString ("address");
                String cont = rs.getInt ("contactNumber") + ""; 
                
                lblName.setText (name);
                lblUsername.setText (username);
                lblBirthdate.setText(birthdate);
                lblAge.setText ("Age: " + age);
                lblAddress.setText ("Address: " + address);
                lblCont.setText ("Contact Number: " + cont);
            }
        } catch (SQLException sqle) {
            String report = "Error in database:\n" + sqle;
            System.err.println ("Database Problem: " + sqle);
            JOptionPane.showMessageDialog (null, report, "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    public void launchFrame() {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            setOpacity (1.0f);
            new ViewUser(connection, UID).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnMin;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBirthdate;
    private javax.swing.JLabel lblCont;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPic;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlPic;
    // End of variables declaration//GEN-END:variables
}
